### ISSUE TITLE
Баги в модели

### ISSUE THREAD

**Issue by gagarski** [Ktlo/PlanetarySystemSimulator#1]
1. Почему-то невозможно создать объект с эксцентриситетом 0. Вкладка, где явно задаётся эксцентриситет этого не позволяет сделать, а если попытаться задать его через размеры полуосей, то вылетает исплючение:
```
May 08, 2018 2:32:46 PM tornadofx.DefaultErrorHandler uncaughtException
SEVERE: Uncaught error
java.lang.IllegalArgumentException: The time is invalid
        at javafx.animation.Animation.jumpTo(Animation.java:754)
        at javafx.animation.Animation.playFrom(Animation.java:868)
        at ktlo.psyssim.model.PlanetarySystem$subPlanet$1.invoke(PlanetarySystem.kt:115)
        at ktlo.psyssim.model.PlanetarySystem$subPlanet$$inlined$with$lambda$1.invoke(PlanetarySystem.kt:133)
        at ktlo.psyssim.model.PlanetarySystem$subPlanet$$inlined$with$lambda$1.invoke(PlanetarySystem.kt:19)
        at ktlo.psyssim.model.PlanetarySystem$sam$javafx_beans_InvalidationListener$0.invalidated(PlanetarySystem.kt)
        at com.sun.javafx.binding.ExpressionHelper$SingleInvalidation.fireValueChangedEvent(ExpressionHelper.java:137)
...
```
2. Если взять шаблон "Inner solar system" и добавить спутник, например, Луне с большим радиусом орбиты, но маленькой массой (оставим все параметры кроме массы по умолчанию, а массу установим в 0.0001), то орбита земли довольно сильно сместится от нарисованной пунктиром. Выглядит это, как минимум, контринтуитивно. Такое ощущение, что при подсчёте центра масс подсистемы не учитываются, собственно, массы.

**Comment by gagarski** [comment]
Диаметр и масса, как минимум, не должны зависеть друг от друга линейно, а лучше бы вообще сделать их независимыми полями.

**Comment by Ktlo** [comment]
Никакой массы на самом деле в программе не было. Я так обозвал радиус. Для устранения недопонимания переименовал в радиус.
Эксцентриситет равный нулю сначала рассматривался, как исключительный случай, который моя программа не симулировала, но сейчас переработал модель и теперь можно установить такой эксцентриситет через равенство полуосей эллипса.
